import '../cli/exit_codes.dart';

/// Base exception class for all errors generated by flutter_app_update_guard.
class GuardException implements Exception {
  final String message;
  final int exitCode;
  final Object? details;

  const GuardException(
    this.message, {
    this.exitCode = ExitCodes.internalError,
    this.details,
  });

  @override
  String toString() {
    if (details != null) {
      return '$message\nDetails: $details';
    }
    return message;
  }
}
